# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.10
  - 3.9
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U Click>=7.0 PyYAML 'pip>=20.0.0,<21.0.0' --force-reinstall

# Command to run tests, e.g. python setup.py test
script: python -m unittest tests/test_conda_env_export.py


