name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.11", "3.10", "3.9", "3.8", "3.7", "3.6"]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -U Click>=7.0 PyYAML 'pip>=20.0.0,<21.0.0' --force-reinstall

    - name: Run tests
      run: python -m unittest tests/test_conda_env_export.py
